### ISSUE TITLE
High Council

### ISSUE THREAD

**Issue by dbergan** [FoxAhead/Civ2-UI-Additions#1]
Thanks for the great Civ2 help!  Just dusted off this classic today and thanks to your help, got everything running.  Or just about everything...

Got the High Council to work fine when running civ2.exe (after using your Civilization-II-64-bit-Editbox-Patcher) with the CD in.  However, when I play the game via Civ2UIALauncher.exe the Advisors --> High Council option doesn't do anything.

So, as is, I have to make a choice... play with the high council (one of my favorite parts of the game) or the UI additions.  Would love to have both!

Thanks!

Kind regards,
David

**Comment by FoxAhead** [comment]
Hi!
To watch intro/wonders movies and High Council movies No-CD patch should be turned off. In Civ2UIALauncher go to Options and turn off "Disable CD check" feature
![image](https://user-images.githubusercontent.com/6097762/36521237-d489db3c-17a6-11e8-95f6-1cdd11e90ed4.png)
Also be sure that your CIV2.EXE is not hard-patched by standalone No-CD patcher and Indeo 4 codec is enabled.
https://forums.civfanatics.com/threads/indeo-codec-troubles-with-civ2-solved.362336/

**Comment by dbergan** [comment]
Awesome!  Thank you so much!  Maybe make a mention of this in the Readme?

Kind regards,
David

**Comment by FoxAhead** [comment]
Done ;)
