### ISSUE TITLE
Unable to Respond During Negotiations with AI

### ISSUE THREAD

**Issue by aryker** [FoxAhead/Civ2-UI-Additions#11]
Hey there,

First off, this patch is amazing! Thanks for all your hard work!

I started a new game with this patch applied yesterday, and after a while I noticed that whenever I am negotiating with an AI, I am never taken to the dialog box titled "You Respond..." with options to ask for tribute, propose trades, etc. This happens whether the negotiation was initiated by myself or the AI. I have tried to do some debugging, but my Pascal-fu is weak and I am not familiar with the memory addresses used by the game (e.g. the WriteMemory call in C2PatchHostileAi). I am happy to help troubleshoot further; just let me know what you need.

The typical dialog path seems to be: Send Emissary -> "Greetings from..." -> [Standard threat/request for tech made by AI] -> "Pleased to speak to you..." -> [End Dialog]

Thanks!

**Comment by aryker** [comment]
Another thing I have noticed, perhaps on a related note, is that moving a Spy into an enemy city does not initiate the typical dialog box that allows you to inspect, sabotage, etc.

**Comment by FoxAhead** [comment]
Hi! It would be easier if I had a save file and steps to reproduce.

**Comment by aryker** [comment]
No problem! Save file is in the attached zip folder, since GitHub won't let me upload a .sav file.
[al_b2460.zip](https://github.com/FoxAhead/Civ2-UI-Additions/files/5831269/al_b2460.zip)


To reproduce the negotiation issue:
1. Click Advisors -> Foreign Minister (or press F3)
2. Select any of the three civilizations on the list and click "Send Emissary"
3. Select "Never! The xxx are our friends." (or whatever equivalent option is presented)
4. Opt not to enter a military alliance if they propose one.
5. Click OK when they say they're happy to talk to you.
6. No response dialog will appear, and the conversation will end.

Te reproduce the Spy dialog issue:
1. Move the Spy in Corinth to the yellow (Spanish) city of Salamanca (she should be the active unit when you load the save).
2. No dialog box will appear.

Let me know if there's anything else I can do to help. Thanks again!

**Comment by FoxAhead** [comment]
![image](https://user-images.githubusercontent.com/6097762/104939354-5f751180-59c1-11eb-93a8-d10a3879da88.png)
![image](https://user-images.githubusercontent.com/6097762/104939363-63a12f00-59c1-11eb-857d-4cf022195f05.png)
![image](https://user-images.githubusercontent.com/6097762/104939434-74ea3b80-59c1-11eb-937e-c804dedabe59.png)

**Comment by aryker** [comment]
Interesting... My selected options are a bit different. These are the ones I had selected up until this point:

![image](https://user-images.githubusercontent.com/5115668/104940321-9296b100-597f-11eb-9bb9-ed40b6245b3c.png)

I tried changing mine to match yours, and still got no dialog. I will try to patch a fresh install and let you know what happens.

**Comment by FoxAhead** [comment]
The same is with negotiations. Did you test it without launcher? If issue reproduces in vanilla game, then maybe it is something with your system config? Do you have multiple monitors. Maybe popup appears somewhere else. Or maybe it is hidden behind other windows. Try to move them around. Or choose from menu View - Arrange Windows.
BTW it is not a patcher. It is a launcher that patches in-memory. So if run civ2.exe directly you should get vanilla game (unless it is patched by some other patches).

**Comment by aryker** [comment]
I get the same result with the vanilla game, so it must be something to do with my system. I'm currently running on a laptop connected to two additional monitors via a Dell Thunderbolt Dock. I will try on a different system later today. Thanks for taking the time to test and clarify, and apologies for taking up your time!

**Comment by FoxAhead** [comment]
![image](https://user-images.githubusercontent.com/6097762/104968050-eb089580-59f5-11eb-9b59-6b99ebd1ef1a.png)
You can use Microsoft Spy++ tool from VS to inspect process' windows and find missing popup. Just check it coordinates (rectangle). Maybe it is really off screen.
