### ISSUE TITLE
Flagged by anivirus (McAfee)

### ISSUE THREAD

**Issue by DARK-STAR03** [FoxAhead/Civ2-UI-Additions#24]
When trying to move the latest stable release patch to my windows xp vm, McAfee detects the files as malware. Also, when trying to download the pre-releases firefox wouldn't download it because it detected the patch as malware too.

Here is a screenshot of the threat codes.

![Screenshot 2023-05-15 172042](https://github.com/FoxAhead/Civ2-UI-Additions/assets/103079244/5daaa76d-1408-4274-b1b6-9c47c94b4c50)

I know GitHub is a reputable site but i just want to be safe.
Hope this gets sorted out soon, have a nice day/night!

**Comment by FoxAhead** [comment]
Reported the False Positive to several AV vendors, including McAfee, and received confirmation of whitelisting. So make sure to update signatures database.
Firefox also doesn't seem to block the file anymore.
Reopen if issue persists.
