### ISSUE TITLE
Dye-Copper bug

### ISSUE THREAD

**Issue by hoclun-rigsep** [FoxAhead/Civ2-UI-Additions#28]
Thank you very much for what you have done here.

It would be neat if you could apply the fix for the Dye-Copper bug from this program!

**Comment by FoxAhead** [comment]
The fix for dye-copper demand bug has long been added to version 1.19 almost two years ago. Does it not work for you?
There is no option for turning it on/off. The fix is always applied as long as you use CIV2UIA.

**Comment by hoclun-rigsep** [comment]
My mistake! I hadn't played in a while and for a minute it seemed like there was anomalous copper demand. Thanks again; it's such a big difference playing without that bug.
