### ISSUE TITLE
Question - Structure [Music]

### ISSUE THREAD

**Issue by shikulja** [FoxAhead/Civ2-UI-Additions#30]
I can find out the complete correct directory structure for music, including subdirectories?

I tried to make the tracks exactly as written in the release. But it seems it’s still impossible to set the tracks manually.
![image](https://github.com/user-attachments/assets/76093d6b-de94-4fe4-b55c-1bb2724b5c60)
![image](https://github.com/user-attachments/assets/96c12af3-beed-4a3f-8546-d43433761b69)
![image](https://github.com/user-attachments/assets/926dc540-522f-4905-b0d3-5cb1aac53bbe)

**Comment by shikulja** [comment]
1. issue found. Not work with translated title in game.txt
2. local files still cant found

**Comment by FoxAhead** [comment]
В первую очередь папка MUSIC ищется там откуда был загружен сэйв или сценарий. Если не найдена, то папка MUSIC ищется в корне игры (там где был запущен CIV2.EXE.
В самой папке MUSIC ищутся файлы с указанными расширениями. Эти файлы не должны быть скрытыми или системными. Используется стандартные функции Windows API: FindFirstFile, FindNextFile.
Учитывая эту информацию могу только пока предположить, что например:

**Comment by FoxAhead** [comment]
В первую очередь папка MUSIC ищется там откуда был загружен сэйв или сценарий. Если не найдена, то папка MUSIC ищется в корне игры (там где был запущен CIV2.EXE.
В самой папке MUSIC ищутся файлы с указанными расширениями. Эти файлы не должны быть скрытыми или системными. Используется стандартные функции Windows API: FindFirstFile, FindNextFile.
Учитывая эту информацию могу только пока предположить, что например:
0) Вставлен компакт диск с игрой (тогда треки читаютя с него)
1) слишком длинный путь до игры
2) ошибка в названии папки MUSIC (например, русские буквы)
3) сейв загружается откуда-то еще, где есть другая папка MUSIC и там другие треки

**Comment by FoxAhead** [comment]
Если запакуете всю папку Civ2 и выложите куда-нибудь, то смогу посмотреть более подробно. В моих условиях сейчас всё работает.

**Comment by shikulja** [comment]
@FoxAhead сейчас залью

**Comment by shikulja** [comment]
@FoxAhead https://mega.nz/file/8A4xCTwB#hT89PUUI_4kFLLhf1k8BEUwXcNvkCUxu9G0cmAu7D7g

**Comment by FoxAhead** [comment]
Скачал, распаковал в D:\MGE. Запустил сходу ничего не меняя через Civ2UIALauncher.exe. Загрузил сэйв Ma_Автом..SAV.

Windows 7:
![image](https://github.com/user-attachments/assets/d065d77c-dfd6-4e24-a48e-aaa6f936b371)

Также проверил на VM Windows 10 21H2.
![image](https://github.com/user-attachments/assets/2bff4f51-1f33-420e-8daa-65be71b1065f)

На VM Windows 10 заметны некоторые проблемы с кодировкой. Возможно это относится к самой сборке Win10. Но как видно, это также не помешало отобразить список треков.

**Comment by shikulja** [comment]
С кодировкой у меня проблем не было, наверно шрифтов не хватает.
А с музыкой не получилось. Пробовал из корня диска C: то же самое, игра просит диск. Переименовать пробовал по-разному, пробовал ogg и flac.. 
Кодеки стоят K-Lite Codec Pack, может быть системные тоже, не уверен.

Если у вас музыка появилась. А у меня нет, скорее всего есть какой-то нюанс.

**Comment by FoxAhead** [comment]
Если игра просит диск, то, возможно, не включена эта опция:

![image](https://github.com/user-attachments/assets/d1d02260-3564-4045-a567-9d4172311b5d)

Её описание устарело, т.к. сейчас установка этой галки включает автоматический режим определения наличия CD, а не просто вырубает чтение с CD.

**Comment by FoxAhead** [comment]
...Хотя если я запускал вашу сборку, то опции должны были из файла Civ2UIALauncher.ini подтянуться. Тогда не монимаю, почему игра требует компакт диск...

**Comment by shikulja** [comment]
Была включена. В дефолте галочки так и стояли вроде.   Может кодеки определенные не видит в системе, которые есть у вас и поэтому не читает ид треков.. 
Должно быть наверно отличие в системе, так как сборку мы проверяем одну.

**Comment by shikulja** [comment]
@FoxAhead работает, висел один образ. недоразмонтировался.. чтоли. то есть был подключен, но игра виртуальный образ не могла прочесть, и локальные файлы не прочитала.
