### ISSUE TITLE
Музыка с директории игры

### ISSUE THREAD

**Issue by shikulja** [FoxAhead/Civ2-UI-Additions#4]
Сделай как Civ2Patch можно было треки записать и играть с музыкой.

**Comment by meustrus** [comment]
I second this, even though I can't read Russian. Google translates the issue as "Music from the game directory", with description "Do as Civ2Patch could record tracks and play with music".

I haven't worked with Delphi before, but I would be willing to help make this happen if you could help me get to a point where I am writing code and describe any of the problems specific to this project.

**Comment by shikulja** [comment]
> I second this, even though I can't read Russian. Google translates the issue as "Music from the game directory", with description "Do as Civ2Patch could record tracks and play with music".
> 
> I haven't worked with Delphi before, but I would be willing to help make this happen if you could help me get to a point where I am writing code and describe any of the problems specific to this project.

I thought the author of the project is Russian, for some reason. I apologize.
The translation is not quite correct, apparently I wrote too easy.

- I want to add the ability to play music as in Civ2Patch
(UI Addition is a replacement for the Civ2Patch, but there is no such opportunity that was there)

================================
Я думал автор проекта русский, почему то. Я извиняюсь. 
Перевод не совсем правильный, видимо я написал слишком просто.

- Я хочу чтобы добавили возможность проигрывать музыку как в Civ2Patch
(UI Addition - замена Civ2Patch но такой возможности, которая была там, нету)

**Comment by meustrus** [comment]
I don't know if @FoxAhead is Russian. All I know is that everything in this repository is in English, except for the three issues you opened.
